apiVersion: v2
name: wave
description: wave chart that runs on kubernetes
version: 2.0.0
appVersion: v0.4.0
keywords:
  - wave
  - kubernetes
home: https://github.com/wave-k8s/wave
sources:
- https://github.com/wave-k8s/wave
maintainers:
  - name: funkypenguin
    email: davidy@funkypenguin.co.nz
    url: https://www.funkypenguin.co.nz
